server:
  port: 8611
  host: 127.0.0.1

feign:
  hystrix:
    enabled: true
    
spring:
  http: 
    encoding: 
      force: true
      charset: UTF-8
      enabled: true
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual # 手动应答
        concurrency: 5 # 消费端最小并发数
        max-concurrency: 10 # 消费端最大并发数
        prefetch: 5 # 一次请求中预处理的消息数量
      retry:
        enabled: true #尝试投递消息，默认false
        max-attempts: 4  #尝试投递消息的最大数量 ,默认3

### 自定义配置
mq:
  defaultExchange: emailExchange # 默认交换器
  queue: emailQueue # 队列名
  routeKey: emailQueueKey # 路由key
      
eureka:
  instance:
    non-secure-port: ${server.port:8611}
    prefer-ip-address: true
    instance-id: ${spring.application.name}(${spring.cloud.client.ipAddress}):${server.port}
  client:
    service-url:
      defaultZone: http://zm:zm123@127.0.0.1:8600/eureka/ 
      
      
pro:
  path: dev-path
         
      